<?php
/** @var Stagem_Estimator_Block_Email_Addons $this */
?>
<!--[if (gte mso 9)|(IE)]>
<table width="600" align="center">
    <tr>
        <td>
<![endif]-->
<table class="outer" align="center" style="Margin: 0 auto; background: #ffffff; border-spacing: 0; color: #3d3d3d; font-family: sans-serif; max-width: 600px; width: 100%;">
    <tr>
        <td class="two-column header" style="font-size: 0; padding: 0; vertical-align: middle; text-align: center;">
            <!--[if (gte mso 9)|(IE)]>
            <table width="100%">
                <tr>
                    <td width="100%" valign="top">
            <![endif]-->
            <div class="column" style="display: inline-block; vertical-align: top; width: 100%;">
                <table width="100%" style=" width: 100%; border-spacing: 0; color: #3d3d3d; font-family: sans-serif;">
	                <?php /** @var Stagem_Estimator_Model_Estimation $estimation */ ?>
	                <?php /** @var Stagem_Estimator_Model_Addon $addon */ ?>
	                <?php $estimation = $this->getEstimation(); ?>
	                <?php $i = 0; foreach($estimation->getAddons() as $addon) : ?>
                    <tr>
                        <td>
                            <!-- line- -->
                            <table width="100%" cellpadding="0" cellspacing="0" border="0" style=" width: 100%; background: #ffffff; margin: auto; padding: 0; border-collapse: collapse; border-spacing: 0; border: 0 none;">
                                <tr>
                                    <td rowspan="30" width="20" height="30" cellpadding="0" cellspacing="0" border="0" style=" width: 20px; height: 30px; vertical-align: top; border-collapse: collapse; border-spacing: 0; border: 0 none;"></td>

                                    <td height="30" cellpadding="0" cellspacing="0" border="0" style="height: 30px; vertical-align: top; border-collapse: collapse; border-spacing: 0; border: 0 none;">
                                        <table class="contents" width="100%" style="border-spacing: 0; <?= (++$i % 2  == 0) ?: 'background: #F3F3F3;' ?> color: #3d3d3d; font-family: sans-serif; font-size: 14px; text-align: left; width: 100%;">
                                            <tr>
                                                <td width="100%" height="10" colspan="2" cellpadding="0" cellspacing="0" border="0" style="width: 100%px; height: 10px; vertical-align: middle; font-size: 10px; line-height: 10px; margin: 0px; padding: 0px; border-collapse: collapse; border-spacing: 0; border: 0 none;">&nbsp;</td>
                                            </tr>

                                            <tr>
                                                <td class="text text__head center" style="font-size: 11px; font-weight: bold; line-height: 16px; padding: 0; text-align: left !important;">
                                                    <p style="font-family: Arial, 'Open Sans', 'Helvetica Neue', Helvetica, sans-serif; font-size: 14px; line-height: 1.42; font-weight: normal; border: 0 none; color: #7D7D7D; text-align: left; vertical-align: top; margin: 0; padding: 0;">
	                                                    <?= $addon->getName() ?>
	                                                    <i><?= $this->getMeasureValue($addon) ?></i>
                                                    </p>
                                                </td>
                                                <td class="text text__head center" style="font-size: 11px; font-weight: bold; line-height: 16px; padding: 0; text-align: left !important;">
                                                    <p style="font-family: Arial, 'Open Sans', 'Helvetica Neue', Helvetica, sans-serif; font-size: 14px; line-height: 1.42; font-weight: normal; border: 0 none; color: #3d3d3d;text-align: right; vertical-align: top; margin: 0; padding: 0;">
	                                                    <?= $this->getPriceValue($addon) ?>
                                                    </p>
                                                </td>
                                            </tr>

                                            <tr>
                                                <td width="100%" height="10" colspan="2" cellpadding="0" cellspacing="0" border="0" style="width: 100%px; height: 10px; vertical-align: middle; font-size: 10px; line-height: 10px; margin: 0px; padding: 0px; border-collapse: collapse; border-spacing: 0; border: 0 none;">&nbsp;</td>
                                            </tr>

                                        </table>
                                    </td>

                                    <td rowspan="30" width="20" height="30" cellpadding="0" cellspacing="0" border="0" style="width: 20px; height: 30px; vertical-align: top; border-collapse: collapse; border-spacing: 0; border: 0 none;"></td>
                                </tr>
                            </table><!-- end line- -->
                        </td>
                    </tr>
	                <?php endforeach; ?>

                </table>
            </div>
            <!--[if (gte mso 9)|(IE)]>
            </td><td width="50%" valign="top">
            <![endif]-->
        </td>
    </tr>
    <tr>
        <td width="" height="40" cellpadding="0" cellspacing="0" border="0" style="height: 40px; vertical-align: middle; font-size: 40px; line-height: 40px; margin: 0px; padding: 0px; border-collapse: collapse; border-spacing: 0; border: 0 none;">&nbsp;</td>
    </tr>
</table>
<!--[if (gte mso 9)|(IE)]>
</td>
</tr>
</table>
<![endif]-->

