<?php
/**
 * The MIT License (MIT)
 * Copyright (c) 2020 Serhii Popov
 * This source file is subject to The MIT License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * https://opensource.org/licenses/MIT
 *
 * @category Popov
 * @package Popov_<package>
 * @author Serhii Popov <popow.serhii@gmail.com>
 * @license https://opensource.org/licenses/MIT The MIT License (MIT)
 */
?>
<!DOCTYPE html
    PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">

<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title></title>

    <!--[if (gte mso 9)|(IE)]>
    <style type="text/css">
        table {border-collapse: collapse;}
    </style>
    <![endif]-->
</head>

<body style="margin: 0; min-width: 100%; padding: 0;">
<center class="wrapper" style="-ms-text-size-adjust: 100%; background-color: #20B5BD; -webkit-text-size-adjust: 100%; table-layout: fixed; width: 100%;">
    <div class="webkit" style="max-width: 600px;">
        <!-- line- -->
        <table cellpadding="0" cellspacing="0" border="0" style="width: 100%; margin: auto; padding: 0; border-collapse: collapse; border-spacing: 0; border: 0 none;">
            <tr>
                <td height="25" cellpadding="0" cellspacing="0" border="0" style="width: 100%; height: 25px; vertical-align: top; border-collapse: collapse; border-spacing: 0; border: 0 none;">&nbsp;</td>
            </tr>
        </table><!-- end line- -->



        <!--[if (gte mso 9)|(IE)]>
        <table width="600" align="center">
            <tr>
                <td>
        <![endif]-->
        <table class="outer" align="center" style="Margin: 0 auto; background: #4c8c8f; border-spacing: 0; color: #ffffff; font-family: sans-serif; max-width: 600px; width: 100%;">

            <tr>
                <td class="two-column header" style="font-size: 0; padding: 0; vertical-align: middle; text-align: center;">
                    <!--[if (gte mso 9)|(IE)]>
                    <table width="100%">
                        <tr>
                            <td width="50%" valign="top">
                    <![endif]-->
                    <div class="column" style="display: inline-block; max-width: 50%; vertical-align: top; width: 100%;">
                        <table width="100%" style="border-spacing: 0; color: #3d3d3d; font-family: sans-serif;">
                            <tr>
                                <td class="inner" style="padding: 10px;">
                                    <table class="contents" style="border-spacing: 0; color: #3d3d3d; font-family: sans-serif; font-size: 14px; text-align: left; width: 100%;">
                                        <tr>
                                            <td class="text text__head center" style="font-size: 17px; font-weight: regular; line-height: 14px; padding: 0; text-align: center; !important;">
                                                <a href="tel:+15143162973" cellpadding="0" cellspacing="0" border="0" target="_blank" style="font-family: Arial, 'Open Sans', 'Helvetica Neue', Helvetica, sans-serif; font-size: 14px; line-height: 1.4; color: #ffffff; font-weight: normal; text-align: center; -webkit-text-size: none; margin: 0; padding: 0; border: 0 none;  text-decoration: none;">
                                                    {{var phones.0}}
                                                </a>
                                            </td>
                                        </tr>
                                    </table>
                                </td>
                            </tr>
                        </table>
                    </div>
                    <!--[if (gte mso 9)|(IE)]>
                    </td><td width="50%" valign="top">
                    <![endif]-->


                    <div class="column" style="display: inline-block; max-width: 50%; vertical-align: top; width: 100%;">
                        <table width="100%" style="border-spacing: 0; color: #3d3d3d; font-family: sans-serif;">
                            <tr>
                                <td class="inner" style="padding: 10px;">
                                    <table class="contents" style="border-spacing: 0; color: #3d3d3d; font-family: sans-serif; font-size: 14px; text-align: left; width: 100%;">
                                        <tr>
                                            <td class="text text__head center" style="font-size: 17px; font-weight: regular; line-height: 14px; padding: 0; text-align: center; !important;">
                                                <a href="tel:+14384485545" cellpadding="0" cellspacing="0" border="0" target="_blank" style="font-family: Arial, 'Open Sans', 'Helvetica Neue', Helvetica, sans-serif; font-size: 14px; line-height: 1.4; color: #ffffff; font-weight: normal; text-align: center; -webkit-text-size: none; margin: 0; padding: 0; border: 0 none;  text-decoration: none;">
                                                    {{var phones.1}}
                                                </a>
                                            </td>
                                        </tr>
                                    </table>
                                </td>
                            </tr>
                        </table>
                    </div>
                    <!--[if (gte mso 9)|(IE)]>
                    </td>
                    </tr>
                    </table>
                    <![endif]-->
                </td>
            </tr>
        </table>
        <!--[if (gte mso 9)|(IE)]>
        </td>
        </tr>
        </table>
        <![endif]-->

        <!--[if (gte mso 9)|(IE)]>
        <table width="600" align="center">
            <tr>
                <td>
        <![endif]-->
        <table class="outer" align="center" style="Margin: 0 auto; background: #ffffff; border-spacing: 0; color: #3d3d3d; font-family: sans-serif; max-width: 600px; width: 100%;">

            <tr>
                <td class="two-column header" style="font-size: 0; padding: 0; vertical-align: middle; text-align: center;">
                    <!--[if (gte mso 9)|(IE)]>
                    <table width="100%">
                        <tr>
                            <td width="50%" valign="top">
                    <![endif]-->
                    <div class="column" style="display: inline-block; max-width: 50%; vertical-align: top; width: 100%;">
                        <table width="100%" style="border-spacing: 0; color: #3d3d3d; font-family: sans-serif;">
                            <tr>
                                <td class="inner" style="padding: 20px;">
                                    <table class="contents" style="border-spacing: 0; color: #3d3d3d; font-family: sans-serif; font-size: 14px; text-align: left; width: 100%;">
                                        <tr>
                                            <td class="text text__head center" style="font-size: 11px; font-weight: bold; line-height: 16px; padding: 0; text-align: left !important;">
                                                <a href="#" cellpadding="0" cellspacing="0" border="0" target="_blank">
                                                    <img src="{{config path='design/header/logo_src'}}" width="138" height="85" alt="{{config path='design/header/logo_alt'}}" cellpadding="0" cellspacing="0" border="0"  style="display: block; margin: 0; Margin: 0; text-aligh: center; padding: 0; border: 0 none;"/>
                                                </a>
                                            </td>
                                        </tr>
                                    </table>
                                </td>
                            </tr>
                        </table>
                    </div>
                    <!--[if (gte mso 9)|(IE)]>
                    </td><td width="50%" valign="top">
                    <![endif]-->
                    <div class="column" style="display: inline-block; max-width: 50%; vertical-align: top; width: 100%;">
                        <table width="100%" style="border-spacing: 0; color: #3d3d3d; font-family: sans-serif;">
                            <tr>
                                <td class="inner" style="padding: 20px 30px;">
                                    <table class="contents" style="border-spacing: 0; color: #979797; font-family: sans-serif; font-size: 14px; text-align: left; width: 100%;">
                                        <tr>
                                            <td class="text text__head center" style="font-size: 17px; font-weight: regular; line-height: 14px; padding: 0; padding-top: 10px; text-align: left !important;">
                                                <p style="font-family: Arial, 'Open Sans', 'Helvetica Neue', Helvetica, sans-serif; font-size: 14px; line-height: 1.2; font-weight: normal; border: 0 none; color: #979797;text-align: left; vertical-align: top; margin: 0; padding: 0; letter-spacing: 0.08em;">
                                                    Add-ons to standerd installation
                                                </p>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td class="text text__head center" style="font-size: 17px; font-weight: regular; line-height: 14px; padding: 0; padding-top: 10px; text-align: left !important;">
                                                <p style="font-family: Arial, 'Open Sans', 'Helvetica Neue', Helvetica, sans-serif; font-size: 14px; line-height: 1.2; font-weight: normal; border: 0 none; color: #979797;text-align: left; vertical-align: top; margin: 0; padding: 0;letter-spacing: 0.08em">
                                                    DATE: DD/MM/YYYY
                                                </p>
                                            </td>
                                        </tr>
                                    </table>
                                </td>
                            </tr>
                        </table>
                    </div>
                    <!--[if (gte mso 9)|(IE)]>
                    </td>
                    </tr>
                    </table>
                    <![endif]-->
                </td>
            </tr>
            <tr>
                <td class="full-width-image" style="padding: 0; background: #ffffff;">
                    <img src="{{skin url='stagem/estimator/img/line-h.png'}}" width="100%" height="21" alt="#" border="0" style="display: block; border: 0 none;"/>
                </td>
            </tr>
            <tr>
                <td height="20" cellpadding="0" cellspacing="0" border="0" style="height: 20px; vertical-align: middle; font-size: 20px; line-height: 20px; margin: 0px; padding: 0px; border-collapse: collapse; border-spacing: 0; border: 0 none;">&nbsp;</td>
            </tr>
        </table>
        <!--[if (gte mso 9)|(IE)]>
        </td>
        </tr>
        </table>
        <![endif]-->


        <!--[if (gte mso 9)|(IE)]>
        <table width="600" align="center">
            <tr>
                <td>
        <![endif]-->
        <table class="outer" align="center" style="Margin: 0 auto; border-spacing: 0; color: #3d3d3d; font-family: sans-serif; max-width: 600px; width: 100%; background: #ffffff;">

            <tr>
                <td class="one-column" style="padding: 0;">
                    <table width="100%" style="border-spacing: 0; color: #3d3d3d; font-family: sans-serif;">
                        <tr>
                            <td class="inner contents" style="padding: 0; text-align: center; width: 100%;">
                                <table width="100%" style="border-spacing: 0; color: #3d3d3d; font-family: sans-serif;">
                                    <tr>
                                        <td class="inner contents" style="padding: 10px; text-align: center; width: 100%;">
                                            <a href="#" cellpadding="0" cellspacing="0" border="0" target="_blank">
                                                <img src="{{var estimation.configurable.getProductUrl()}}" width="220" height="230" alt="{{var estimation.getConfigurable().getName()}} {{var estimation.getProduct().getName()}}" cellpadding="0" cellspacing="0" border="0"  style="display: block; margin: 0; Margin: 0 auto; text-aligh: center; padding: 0; border: 0 none;"/>
                                            </a>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td align="center" class="inner contents" style="text-align: center; width: 100%;">
                                            <a href="#" cellpadding="0" cellspacing="0" border="0" target="_blank" style="font-family: 'Open Sans', 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 15px; line-height: 1.4; color: #3d3d3d; font-weight: normal; text-align: center; -webkit-text-size: none; margin: 0; padding: 0; border: 0 none; text-decoration: none;">
                                                {{var estimation.getConfigurable().getName()}}
                                                <br>
                                                <b>{{var estimation.getProduct().getName()}}</b>
                                            </a>
                                        </td>
                                    </tr>
                                </table>
                            </td>
                        </tr>
                    </table>
                </td>
            </tr>

        </table>
        <!--[if (gte mso 9)|(IE)]>
        </td>
        </tr>
        </table>
        <![endif]-->

        <!--[if (gte mso 9)|(IE)]>
        <table width="600" align="center">
            <tr>
                <td>
        <![endif]-->
        <table class="outer" align="center" style="Margin: 0 auto; border-spacing: 0; color: #3d3d3d; font-family: sans-serif; max-width: 600px; width: 100%; background: #ffffff;">

            <tr>
                <td class="one-column" style="padding: 0;">
                    <table width="100%" style="border-spacing: 0; color: #3d3d3d; font-family: sans-serif;">
                        <tr>
                            <td class="inner contents" style="padding: 20px 30px; text-align: center; width: 100%;">
                                <table width="100%" style="border-spacing: 0; color: #3d3d3d; font-family: sans-serif;">
                                    <tr>
                                        <td class="inner contents" style="padding: 10px 30px; text-align: center; width: 100%;">
                                            <p class="h1" style="Margin: 0; color: #3d3d3d; font-size: 24px; font-weight: noremal; line-height: 140%; text-align: center; letter-spacing: 0.05em;">Thank you for making estimation <br>online with us!</p>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td class="inner contents" style="padding: 10px 30px; text-align: center; width: 100%;">
                                            <p class="h1" style="Margin: 0; color: #8D8D8D; font-size: 14px; font-weight: noremal; line-height: 140%; text-align: center; letter-spacing: 0.05em;">
                                                {{var estimation.getCustomerValue('full_name')]}}, here are you price and offer
                                            </p>
                                        </td>
                                    </tr>
                                </table>
                            </td>
                        </tr>
                    </table>
                </td>
            </tr>

        </table>
        <!--[if (gte mso 9)|(IE)]>
        </td>
        </tr>
        </table>
        <![endif]-->





        <!--[if (gte mso 9)|(IE)]>
        <table width="600" align="center">
            <tr>
                <td>
        <![endif]-->
        <table class="outer" align="center" style="Margin: 0 auto; background: #ffffff; border-spacing: 0; color: #3d3d3d; font-family: sans-serif; max-width: 600px; width: 100%;">

            <tr>
                <td class="two-column header" style="font-size: 0; padding: 0; vertical-align: middle; text-align: center;">
                    <!--[if (gte mso 9)|(IE)]>
                    <table width="100%">
                        <tr>
                            <td width="50%" valign="top">
                    <![endif]-->
                    <div class="column" style="display: inline-block; max-width: 30%; vertical-align: top; width: 100%;">
                        <table width="100%" style="border-spacing: 0; color: #3d3d3d; font-family: sans-serif;">
                            <tr>
                                <td class="inner" style="padding: 20px 30px;">
                                    <table class="contents" style="border-spacing: 0; color: #3d3d3d; font-family: sans-serif; font-size: 14px; text-align: left; width: 100%;">
                                        <tr>
                                            <td class="text text__head center" style="font-size: 11px; font-weight: bold; line-height: 16px; padding: 0; text-align: left !important;">
                                                <p style="font-family: Arial, 'Open Sans', 'Helvetica Neue', Helvetica, sans-serif; font-size: 24px; line-height: 1.42; font-weight: normal; border: 0 none; color: #3d3d3d;text-align: left; vertical-align: top; margin: 0; padding: 0;">Total</p>
                                            </td>
                                        </tr>
                                    </table>
                                </td>
                            </tr>
                        </table>
                    </div>
                    <!--[if (gte mso 9)|(IE)]>
                    </td><td width="50%" valign="top">
                    <![endif]-->
                    <div class="column" style="display: inline-block; max-width: 70%; vertical-align: top; width: 100%;">
                        <table width="100%" style="border-spacing: 0; color: #3d3d3d; font-family: sans-serif;">
                            <tr>
                                <td class="inner" style="padding: 20px 30px;">
                                    <p style="font-family: Arial, 'Open Sans', 'Helvetica Neue', Helvetica, sans-serif; font-size: 24px; line-height: 1.42; font-weight: normal; border: 0 none; color: #3d3d3d;text-align: right; vertical-align: top; margin: 0; padding: 0;">100.25$ + Tax</p>
                                </td>
                            </tr>
                        </table>
                    </div>
                    <!--[if (gte mso 9)|(IE)]>
                    </td>
                    </tr>
                    </table>
                    <![endif]-->
                </td>
            </tr>
            <tr>
                <td class="full-width-image" style="padding: 0; background: #ffffff;">
                    <img src="{{skin url='stagem/estimator/img/line-e.png'}}" width="100%" height="21" alt="#" border="0" style="display: block; border: 0 none;"/>
                </td>
            </tr>
        </table>
        <!--[if (gte mso 9)|(IE)]>
        </td>
        </tr>
        </table>
        <![endif]-->


        <!--[if (gte mso 9)|(IE)]>
        <table width="600" align="center">
            <tr>
                <td>
        <![endif]-->
        <table class="outer" align="center" style="Margin: 0 auto; border-spacing: 0; color: #3d3d3d; font-family: sans-serif; max-width: 600px; width: 100%; background: #ffffff;">

            <tr>
                <td class="one-column" style="padding: 0;">
                    <table width="100%" style="border-spacing: 0; color: #3d3d3d; font-family: sans-serif;">
                        <tr>
                            <td class="inner contents" style="padding: 0; text-align: center; width: 100%;">
                                <table width="100%" style="border-spacing: 0; color: #3d3d3d; font-family: sans-serif;">
                                    <tr>
                                        <td class="inner contents" style="padding: 10px; text-align: center; width: 100%;">
                                            <a href="{{store url='estimator/online/ready' hash=$estimation.getUniq()}}" target="_blank" style="text-decoration:none !important;-ms-text-size-adjust:none;font-family: Arial, 'Open Sans', 'Helvetica Neue', Helvetica, sans-serif;font-size:18px;color:#FFFFFF;border-style:solid;border-color:#20B5BD;border-width:20px 100px;display:inline-block;background:#20B5BD;border-radius:6px;font-weight:normal;font-style:normal;line-height:22px;width:auto;text-align:center;" rel="noreferrer noopener">
                                                {{translate text="Ready to Install"}}
                                            </a>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td align="center" class="inner contents" style="text-align: center; width: 100%;">
                                            <a align="center" href="{{store url='estimator/online/modify' hash=$estimation.getUniq()}}" cellpadding="0" cellspacing="0" border="0" target="_blank" style="font-family:  Arial, 'Open Sans', 'Helvetica Neue', Helvetica, sans-serif; font-size: 14px; line-height: 30px; color: #3d3d3d; font-weight: normal; text-align: center; -webkit-text-size: none; margin: 0; padding: 0; border: 0 none;">
                                                {{translate text="Modify Estimation"}}
                                            </a>
                                        </td>
                                    </tr>
                                </table>
                            </td>
                        </tr>
                        <tr>
                            <td width="" height="20" cellpadding="0" cellspacing="0" border="0" style="height: 20px; vertical-align: middle; font-size: 20px; line-height: 20px; margin: 0px; padding: 0px; border-collapse: collapse; border-spacing: 0; border: 0 none;">&nbsp;</td>
                        </tr>
                        <tr>
                            <td class="full-width-image" style="padding: 0; background: #ffffff;">
                                <img src="{{skin url='stagem/estimator/img/line-r.png'}}" width="100%" height="21" alt="#" border="0" style="display: block; border: 0 none;"/>
                            </td>
                        </tr>
                    </table>
                </td>
            </tr>

        </table>
        <!--[if (gte mso 9)|(IE)]>
        </td>
        </tr>
        </table>
        <![endif]-->


        <!--[if (gte mso 9)|(IE)]>
        <table width="600" align="center">
            <tr>
                <td>
        <![endif]-->
        <table class="outer" align="center" style="Margin: 0 auto; border-spacing: 0; color: #3d3d3d; font-family: sans-serif; max-width: 600px; width: 100%; background: #ffffff;">

            <tr>
                <td class="one-column" style="padding: 0;">
                    <table width="100%" style="border-spacing: 0; color: #3d3d3d; font-family: sans-serif;">
                        <tr>
                            <td class="inner contents" style="padding: 20px 30px; text-align: center; width: 100%;">
                                <table width="100%" style="border-spacing: 0; color: #3d3d3d; font-family: sans-serif;">
                                    <tr>
                                        <td width="" height="20" cellpadding="0" cellspacing="0" border="0" style="height: 20px; vertical-align: middle; font-size: 20px; line-height: 20px; margin: 0px; padding: 0px; border-collapse: collapse; border-spacing: 0; border: 0 none;">&nbsp;</td>
                                    </tr>
                                    <tr>
                                        <td class="inner contents" style="text-align: left; width: 100%;">
                                            <p class="h1" style="Margin: 0; color: #3d3d3d; font-size: 24px; font-weight: noremal; line-height: 140%; text-align: left; letter-spacing: 0.05em;">
                                                {{translate text="All details"}}
                                            </p>
                                        </td>
                                    </tr>
                                </table>
                            </td>
                        </tr>
                    </table>
                </td>
            </tr>

        </table>
        <!--[if (gte mso 9)|(IE)]>
        </td>
        </tr>
        </table>
        <![endif]-->

        <?php echo $this->getLayout()
            ->createBlock('core/template')
            ->setArea('frontend')
            ->setData('estimation', $this->getEstimation())
            ->setTemplate('stagem/estimator/email/addons.phtml')
            ->toHtml()
        ?>

        <!--[if (gte mso 9)|(IE)]>
        <table width="600" align="center">
            <tr>
                <td>
        <![endif]-->
        <table class="outer" align="center" style="Margin: 0 auto; border-spacing: 0; color: #3d3d3d; font-family: sans-serif; max-width: 600px; width: 100%; background: #3d3d3d;">

            <tr>
                <td class="one-column" style="padding: 0;">
                    <table width="100%" style="border-spacing: 0; color: #3d3d3d; font-family: sans-serif;">
                        <tr>
                            <td class="inner contents" style="padding: 10px 30px; text-align: center; width: 100%;">
                                <table width="100%" style="border-spacing: 0; color: #ffffff; font-family: sans-serif;">
                                    <tr>
                                        <td height="20" cellpadding="0" cellspacing="0" border="0" style="height: 20px; vertical-align: middle; font-size: 20px; line-height: 20px; margin: 0px; padding: 0px; border-collapse: collapse; border-spacing: 0; border: 0 none;">&nbsp;</td>
                                    </tr>
                                    <tr>
                                        <td class="inner contents" style="padding: 0 30px; text-align: center; width: 100%;">
                                            <!-- line- -->
                                            <table cellpadding="0" cellspacing="0" border="0" style="width: 100%; margin: auto; padding: 0; border-collapse: collapse; border-spacing: 0; border: 0 none;">
                                                <tr>
                                                    <td height="25" cellpadding="0" cellspacing="0" border="0" style="height: 25px; vertical-align: top; border-collapse: collapse; border-spacing: 0; border: 0 none;"></td>
                                                    <td width="220" height="25" cellpadding="0" cellspacing="0" border="0" style="width: 220px; height: 25px; vertical-align: top; border-collapse: collapse; border-spacing: 0; border: 0 none;">
                                                        <a href="#" cellpadding="0" cellspacing="0" border="0" target="_blank" style="font-family: 'Open Sans', 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 15px; line-height: 1.4; color: #ffffff; font-weight: normal; text-align: left; -webkit-text-size: none; margin: 0; padding: 0; border: 0 none; text-decoration: none;">Help </a>
                                                        <a href="#" cellpadding="0" cellspacing="0" border="0" target="_blank" style="font-family: 'Open Sans', 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 15px; line-height: 1.4; color: #ffffff; font-weight: normal; text-align: left; -webkit-text-size: none; margin: 0; padding: 0; border: 0 none; text-decoration: none;">| Feedback |</a>
                                                        <a href="#" cellpadding="0" cellspacing="0" border="0" target="_blank" style="font-family: 'Open Sans', 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 15px; line-height: 1.4; color: #ffffff; font-weight: normal; text-align: left; -webkit-text-size: none; margin: 0; padding: 0; border: 0 none; text-decoration: none;"> About Us</a>
                                                    </td>
                                                    <td height="25" cellpadding="0" cellspacing="0" border="0" style="height: 25px; vertical-align: top; border-collapse: collapse; border-spacing: 0; border: 0 none;"></td>
                                                </tr>
                                            </table><!-- end line- -->
                                        </td>
                                    </tr>
                                    <tr>
                                        <td height="20" cellpadding="0" cellspacing="0" border="0" style="width: 100%; height: 20px; vertical-align: middle; font-size: 20px; line-height: 20px; margin: 0px; padding: 0px; border-collapse: collapse; border-spacing: 0; border: 0 none;">
                                            <img src="{{skin url='stagem/estimator/img/line-f.png'}}" width="100%" height="30" alt="#" border="0" style="display: block; border: 0 none;"/>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td class="inner contents" style="padding: 0 30px; text-align: center; width: 100%;">
                                            <p class="h1" style="Margin: 0; color: #b1b1b1; font-size: 11px; font-weight: noremal; line-height: 100%; text-align: center; letter-spacing: 0.05em;">
                                                Please note that deals are subject to availabilty and its prices are subject to change
                                            </p>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td class="inner contents" style="padding: 10px 30px; text-align: center; width: 100%;">
                                            <p class="h1" style="Margin: 0; color: #b1b1b1; font-size: 11px; font-weight: noremal; line-height: 140%; text-align: center; letter-spacing: 0.05em;">
                                                Have an issue that we can help with? Email us at <a href="mailto:sales@airgreen.ca" style="color:#2199e8;font-family:sans-serif;font-weight:400;padding:0;margin:0;text-decoration:none;">sales@airgreen.ca</a> or write to us at 4951 St Catherine St E, Montreal, Quebec.
                                                <br/>Learn about our Privacy Policy
                                            </p>
                                        </td>
                                    </tr>
                                </table>
                            </td>
                        </tr>
                    </table>
                </td>
            </tr>

        </table>
        <!--[if (gte mso 9)|(IE)]>
        </td>
        </tr>
        </table>
        <![endif]-->

        <table cellpadding="0" cellspacing="0" border="0" style="width: 100%; margin: auto; padding: 0; border-collapse: collapse; border-spacing: 0; border: 0 none;">
            <tr>
                <td height="25" cellpadding="0" cellspacing="0" border="0" style="width: 100%; height: 25px; vertical-align: top; border-collapse: collapse; border-spacing: 0; border: 0 none;">&nbsp;</td>
            </tr>
        </table><!-- end line- -->
    </div>
</center>
</body></html>

