<?php
/**
 * The MIT License (MIT)
 * Copyright (c) 2020 Stagem
 * This source file is subject to The MIT License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * https://opensource.org/licenses/MIT
 *
 * @category Stagem
 * @package Stagem_Estimator
 * @author Serhii Popov <popow.serhii@gmail.com>
 * @license https://opensource.org/licenses/MIT The MIT License (MIT)
 */
?>
<table class="contents" style="border-spacing: 0; color: #979797; font-family: sans-serif; font-size: 14px; text-align: left; width: 100%;">
    <tr>
        <td class="text text__head center" style="font-size: 17px; font-weight: regular; line-height: 14px; padding: 0; padding-top: 10px; text-align: left !important;">
            <p style="font-family: Arial, 'Open Sans', 'Helvetica Neue', Helvetica, sans-serif; font-size: 14px; line-height: 1.2; font-weight: normal; border: 0 none; color: #979797;text-align: left; vertical-align: top; margin: 0; padding: 0; letter-spacing: 0.08em;">
                <?= $this->__('Add-ons to standerd installation') ?>
            </p>
        </td>
    </tr>
    <tr>
        <td class="text text__head center" style="font-size: 17px; font-weight: regular; line-height: 14px; padding: 0; padding-top: 10px; text-align: left !important;">
            <p style="font-family: Arial, 'Open Sans', 'Helvetica Neue', Helvetica, sans-serif; font-size: 14px; line-height: 1.2; font-weight: normal; border: 0 none; color: #979797;text-align: left; vertical-align: top; margin: 0; padding: 0;letter-spacing: 0.08em">
                <?= $this->__('DATE') ?>: <?= (new DateTime())->format('d/m/Y') ?>
            </p>
        </td>
    </tr>
</table>
