<?php
/**
 * The MIT License (MIT)
 * Copyright (c) 2020 Stagem
 * This source file is subject to The MIT License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * https://opensource.org/licenses/MIT
 *
 * @category Stagem
 * @package Stagem_Estimator
 * @author Serhii Popov <popow.serhii@gmail.com>
 * @license https://opensource.org/licenses/MIT The MIT License (MIT)
 */
?>

<table class="contents" style="border-spacing: 0; color: #3d3d3d; font-family: sans-serif; font-size: 14px; text-align: left; width: 100%;">
	<?php /*<tr>
		<td class="text text__head center" style="font-size: 17px; font-weight: regular; line-height: 14px; padding: 0; padding-top: 10px; text-align: left !important;">
			<p style="font-family: Arial, 'Open Sans', 'Helvetica Neue', Helvetica, sans-serif; font-size: 14px; line-height: 1.2; font-weight: normal; border: 0 none; color: #3d3d3d;text-align: left; vertical-align: top; margin: 0; padding: 0; letter-spacing: 0.08em;">Add-ons to standerd<br>installation</p>
		</td>
	</tr>*/ ?>
	<tr>
		<td class="text text__head center" style="font-size: 14px; font-weight: regular; line-height: 14px; padding: 0; padding-top: 10px; text-align: left !important;">
			<p style="font-family: Arial, 'Open Sans', 'Helvetica Neue', Helvetica, sans-serif; font-size: 14px; line-height: 1.2; font-weight: normal; border: 0 none; color: #3d3d3d;text-align: left; vertical-align: top; margin: 0; padding: 0; letter-spacing: 0.08em;">
                <?= $this->__('Sent date') ?>: <?= (new DateTime())->format('d/m/Y') ?>
			</p>
		</td>
	</tr>
	<tr>
		<td width="" height="10" cellpadding="0" cellspacing="0" border="0" style="width: px; height: 10px; vertical-align: middle; font-size: 10px; line-height: 10px; margin: 0px; padding: 0px; border-collapse: collapse; border-spacing: 0; border: 0 none;">
			<?php $customer = $this->getCustomer(); ?>
			<p style="font-family: Arial, 'Open Sans', 'Helvetica Neue', Helvetica, sans-serif; font-size: 14px; line-height: 1.42; font-weight: bold; border: 0 none; color: #3d3d3d;text-align: left; vertical-align: top; margin: 0; padding: 0;">
				<?= $customer['full_name'] ?>
			</p>
			<p style="font-family: Arial, 'Open Sans', 'Helvetica Neue', Helvetica, sans-serif; font-size: 14px; line-height: 1.42; font-weight: normal; border: 0 none; color: #3d3d3d;text-align: left; vertical-align: top; margin: 0; padding: 0;">
                <?= $customer['address'] ?>. <?= $customer['zip'] ?>
			</p>
			<p style="font-family: Arial, 'Open Sans', 'Helvetica Neue', Helvetica, sans-serif; font-size: 14px; line-height: 1.42; font-weight: normal; border: 0 none; color: #3d3d3d;text-align: left; vertical-align: top; margin: 0; padding: 0;">
				<a href="mailto:<?= $customer['email'] ?>" cellpadding="0" cellspacing="0" border="0" target="_blank" style="font-family: 'Open Sans', 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 14px; line-height: 1.4; color: #3d3d3d; font-weight: normal; text-align: left; -webkit-text-size: none; margin: 0; padding: 0; border: 0 none; text-decoration: none">
                    <?= $customer['email'] ?>
				</a>
			</p>
			<p style="font-family: Arial, 'Open Sans', 'Helvetica Neue', Helvetica, sans-serif; font-size: 14px; line-height: 1.42; font-weight: normal; border: 0 none; color: #3d3d3d;text-align: left; vertical-align: top; margin: 0; padding: 0;">
				<a href="phone:<?= $customer['phone'] ?>" cellpadding="0" cellspacing="0" border="0" target="_blank" style="font-family: 'Open Sans', 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 14px; line-height: 1.4; color: #3d3d3d; font-weight: normal; text-align: left; -webkit-text-size: none; margin: 0; padding: 0; border: 0 none; text-decoration: none">
					<?= $customer['phone'] ?>
				</a>
			</p>
		</td>
	</tr>
</table>
