<?php
/**
 * The MIT License (MIT)
 * Copyright (c) 2020 Stagem
 * This source file is subject to The MIT License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * https://opensource.org/licenses/MIT
 *
 * @category Stagem
 * @package Stagem_EstimatorOnline
 * @author Serhii Popov <popow.serhii@gmail.com>
 * @license https://opensource.org/licenses/MIT The MIT License (MIT)
 */
?>

<!--[if (gte mso 9)|(IE)]>
<table width="600" align="center">
    <tr>
        <td>
<![endif]-->
<table class="outer" align="center" style="Margin: 0 auto; background: #3194a4d9; border-spacing: 0; color: #ffffff; font-family: sans-serif; max-width: 600px; width: 100%;">
    <tr>
        <td class="two-column header" style="font-size: 0; padding: 0; vertical-align: middle; text-align: center;">

	        <!--[if (gte mso 9)|(IE)]>
	        <table width="100%">
		        <tr>
			        <td width="100%" valign="top">
	        <![endif]-->
	        <div class="column" style="display: inline-block; max-width: 100%; vertical-align: top; width: 100%;">
		        <table width="100%" style="border-spacing: 0; color: #ffffff; font-family: sans-serif;">
			        <tr>
				        <td class="inner" style="padding: 10px;">
					        <table class="contents" style="border-spacing: 0; color: #ffffff; font-family: sans-serif; font-size: 14px; text-align: center; width: 100%;">
						        <tr>
							        <td class="text text__head center" style="font-size: 16px; font-weight: regular; line-height: 14px; padding: 0; text-align: center; !important;">
								        <p style="font-size: 16px;"><?= $this->__('Heating when you need it. Cooling when you want it.') ?></p>
							        </td>
						        </tr>
					        </table>
				        </td>
			        </tr>
		        </table>
	        </div>
	        <!--[if (gte mso 9)|(IE)]>
	                </td>
	            </tr>
	        </table>
	        <![endif]-->

        </td>
    </tr>
</table>
<!--[if (gte mso 9)|(IE)]>
        </td>
    </tr>
</table>
<![endif]-->
