<?php
/**
 * The MIT License (MIT)
 * Copyright (c) 2020 Serhii Popov
 * This source file is subject to The MIT License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * https://opensource.org/licenses/MIT
 *
 * @category Popov
 * @package Popov_<package>
 * @author Serhii Popov <popow.serhii@gmail.com>
 * @license https://opensource.org/licenses/MIT The MIT License (MIT)
 */
?>

<!--[if (gte mso 9)|(IE)]>
<table width="600" align="center">
    <tr>
        <td>
<![endif]-->
<table class="outer" align="center" style="Margin: 0 auto; background: #4c8c8f; border-spacing: 0; color: #ffffff; font-family: sans-serif; max-width: 600px; width: 100%;">

    <tr>
        <td class="two-column header" style="font-size: 0; padding: 0; vertical-align: middle; text-align: center;">
	        <?php foreach ($this->getPhones() as $phone) : ?>
            <!--[if (gte mso 9)|(IE)]>
            <table width="100%">
                <tr>
                    <td width="50%" valign="top">
            <![endif]-->
            <div class="column" style="display: inline-block; max-width: 50%; vertical-align: top; width: 100%;">
                <table width="100%" style="border-spacing: 0; color: #3d3d3d; font-family: sans-serif;">
                    <tr>
                        <td class="inner" style="padding: 10px;">
                            <table class="contents" style="border-spacing: 0; color: #3d3d3d; font-family: sans-serif; font-size: 14px; text-align: center; width: 100%;">
                                <tr>
                                    <td class="text text__head center" style="font-size: 17px; font-weight: regular; line-height: 14px; padding: 0; text-align: center; !important;">
                                        <a href="tel:<?= $phone ?>" cellpadding="0" cellspacing="0" border="0" target="_blank" style="font-family: Arial, 'Open Sans', 'Helvetica Neue', Helvetica, sans-serif; font-size: 14px; line-height: 1.4; color: #ffffff; font-weight: normal; text-align: center; -webkit-text-size: none; margin: 0; padding: 0; border: 0 none;  text-decoration: none;">
                                            <?= $phone ?>
                                        </a>
                                    </td>
                                </tr>
                            </table>
                        </td>
                    </tr>
                </table>
            </div>
            <!--[if (gte mso 9)|(IE)]>
            </td><td width="50%" valign="top">
            <![endif]-->
	        <?php endforeach; ?>

            <!--[if (gte mso 9)|(IE)]>
            </td>
            </tr>
            </table>
            <![endif]-->
        </td>
    </tr>
</table>
<!--[if (gte mso 9)|(IE)]>
</td>
</tr>
</table>
<![endif]-->
