<?php
/**
 * The MIT License (MIT)
 * Copyright (c) 2020 Serhii Popov
 * This source file is subject to The MIT License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * https://opensource.org/licenses/MIT
 *
 * @category Popov
 * @package Popov_<package>
 * @author Serhii Popov <popow.serhii@gmail.com>
 * @license https://opensource.org/licenses/MIT The MIT License (MIT)
 */
?>

<?php $num = count($this->getPhones()); ?>
<?php foreach ($this->getPhones() as $i => $phone) : ?>
	<a href="tel:<?= $phone ?>" cellpadding="0" cellspacing="0" border="0" target="_blank" style="font-family: Arial, 'Open Sans', 'Helvetica Neue', Helvetica, sans-serif; font-size: 18px; line-height: 1.4; color: #333333; font-weight: bold; text-align: center; -webkit-text-size: none; margin: 0; padding: 0; border: 0 none;  text-decoration: none;"><?= $phone ?></a>
	<?php if ($num > $i + 1) : ?>
		<br>
	<?php endif; ?>
<?php endforeach; ?>
