<?php
/**
 * The MIT License (MIT)
 * Copyright (c) 2020 Serhii Popov
 * This source file is subject to The MIT License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * https://opensource.org/licenses/MIT
 *
 * @category Stagem
 * @package Stagem_Estimator
 * @author Serhii Popov <popow.serhii@gmail.com>
 * @license https://opensource.org/licenses/MIT The MIT License (MIT)
 */
?>
<?php
/**
 * @var $this Stagem_Estimator_Block_Estimator
 */
?>
<div>
	<ul>
		<?php foreach ($this->getCategories() as $category) : ?>
		<li data-id="<?= $category->getId() ?>"><?= $category->getName() ?></li>
		<?php endforeach; ?>
	</ul>
</div>

<div>
	<ul>
	<?php foreach ($this->getCategories() as $category) : ?>
		<?php // @TODO Try this one for performance https://stackoverflow.com/a/20898132/1335142 ?>
		<?php foreach ($this->getConfigurables($category) as $configurable) : ?>
			<li data-id="<?= $configurable->getId() ?>">
				<?= $configurable->getName() ?>
				<ul>
					<?php foreach ($this->getProducts($configurable) as $simple) : ?>
						<li data-id="<?= $simple->getId() ?>"><?= $simple->getName() ?></li>
                    <?php endforeach; ?>
				</ul>
			</li>
        <?php endforeach; ?>
	<?php endforeach; ?>
	</ul>
</div>
